- hosts: all
  become: True

  tasks:
    - name: update apt package index
      ansible.builtin.apt:
        update_cache: yes
    - name: install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
        state: present
    
    - name: Ensure destination directory exists
      file:
        path: /home/vagrant/app
        state: directory
    - name: Clone application repo
      git:
       repo: https://github.com/Leilasinore/yolo.git
       dest: /home/vagrant/app
       clone: yes
       update: yes
       version: master
    - name: add Docker official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository for Ubuntu 20.04 (Focal)
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker and Docker Compose
      apt:
        name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose
        state: present
    - name: Enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true
    - name: Add vagrant user to Docker group
      user:
        name: vagrant
        groups: docker
        append: yes
    - name: Start MongoDB using docker-compose
      community.docker.docker_compose_v2:
       project_src: /home/vagrant/app
       services:
        - app-yolo-ip-mongo
       state: present
       recreate: always
       remove_orphans: yes
      tags: db
    - name: Start backend using docker-compose
      community.docker.docker_compose_v2:
       project_src: /home/vagrant/app
       services:
        - leila-yolo-backend
       state: present
       remove_orphans: yes
      tags: backend
    - name: Start frontend using docker-compose
      community.docker.docker_compose_v2:
       project_src: /home/vagrant/app
       services:
        - leila-yolo-frontend
       state: present
       recreate: always
       remove_orphans: yes
      tags: frontend
    - name: Ensure OpenSSL legacy provider is enabled
      lineinfile:
       path: /etc/environment
       line: 'NODE_OPTIONS=--openssl-legacy-provider'
       create: yes
    
   
    