#SPDX-License-Identifier: MIT-0
---
# tasks file for docker_setup
- name: add Docker official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository for Ubuntu 20.04 (Focal)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Install Docker and Docker Compose
  apt:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd.io
     - docker-compose
    state: present
- name: Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
- name: Add vagrant user to Docker group
  user:
    name: vagrant
    groups: docker
    append: yes
