#SPDX-License-Identifier: MIT-0
---
# tasks file for system_setup

- name: System setup tasks
  block:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required system packages
      ansible.builtin.apt:
        name: "{{ system_packages }}"
        state: present

    - name: Ensure app directory exists
      file:
        path: "{{ app_directory }}"
        state: directory

    - name: Clone application repository
      git:
        repo: "{{ app_repo_url }}"
        dest: "{{ app_directory }}"
        clone: yes
        update: yes
        version: "{{ app_repo_branch }}"
  tags: system


