#SPDX-License-Identifier: MIT-0
---
# tasks file for docker_setup

- name: Set up Docker and Docker Compose
  block:
    - name: Add Docker official GPG key
      ansible.builtin.apt_key:
        url: "{{ docker_gpg_key_url }}"
        state: present

    - name: Add Docker repository for Ubuntu
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add vagrant user to Docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

  tags: docker
